app:
 container_name: lxvi-web
 image: golang:1.6
 working_dir: /go/src/
 command: go run ../main.go

 volumes:
 - .:/go/src/
 - ../:/go/
 ports:
 - "8080:8080"
 restart: always
 log_driver: "json-file"

